# Сети глубокого обучения и компьютерное зрение 

## Лабораторная работа №1 "Обработка многомерных массивов в библиотеке NumPy с использованием IPython"

Выполнил студент Оболенский Д.М группы ИСм-21о.

### Интерпретатор IPython и оболочка Jupyter

Интерпретатор **IPython** является полезным интерактивным интерфейсом для языка Python и предоставляет некоторые удобные инструменты для отладки, анализа процесса выполнения программ на языке Python.

**Jupyter** - веб-оболочка для интерпретатора IPython, позволяющая объединить код, текст, формулы и диаграммы в единый документ (*блокнот Jupyter*) и распространять их для других пользователей.

Пример работы с разметкой среды Jupyter можно посмотреть в этом блокноте и в [блокноте с разнообразными примерами использования символов и тегов разметки](https://github.com/jupyter/notebook/blob/master/docs/source/examples/Notebook/Working%20With%20Markdown%20Cells.ipynb)

Для быстрого доступа к документации и другой соответствующей информации в IPython используется знак `?`. Например справку по команде `len` можно поучить так:

In [ ]:
?len

Такой подход можно применять к любым функциям и методам в IPython.

In [261]:
L = [1,2,3]
L.insert?

#### "Магические" команды IPython
"Магические" команды позволяют организовывать выполнение подпрограмм в среде IPython, а также их профилирование, отладку и другие операиции, не связанные непосредственно с языком Python. Например, кманда `%run <скрипт>` запускает в интерактивной оболочке IPython скрипт на Python, а `%timeit`автоматически определяет время выполнения следующего за ней однострочного оператора. Эта команда будет выполнять множественные запуски с целью получения максимально надежных результатов. 

In [262]:
%timeit L = [n ** 2 for n in range(1000)]

562 µs ± 20.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Справку по магическим функциям можно получить при помощи знака `?`. Например:

In [263]:
%timeit?

Для доступа к общему описанию доступных «магических» функций введите команду:

In [264]:
%magic

Для быстрого получения простого списка всех доступных «магических» функций:

In [265]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python2  %%py

С помощью «магической» функции %xmode (сокращение от exception mode — режим отображения исключений) мы можем управлять тем, какая информация будет выведена.
Функция %xmode принимает на входе один аргумент, режим, для которого есть три значения: Plain (Простой), Context (По контексту) и Verbose (Расширенный).

#### Отладка и профилирование.

Отладчик в оболочке IPython называется ipdb (сокращение от IPython Debugger — «отладчик IPython»).

Интерфейс для отладки в IPython — «магическая» команда `%debug`. Если ее вызвать после столкновения с исключением, она автоматически откроет интерактивную командную строку откладки в точке возникновения исключения. Командная строка ipdb позволяет изучать текущее состояние стека, доступные переменные и даже выполнять команды Python.
Для подробной информации воспользуйтесь командой help в отладчике или загляните в [онлайн-документацию по ipdb](https://github.com/gotcha/ipdb)

Оболочка IPython предоставляет широкий выбор функциональности для выполнения подобного мониторинга скорости выполнения кода и его профилирования. Для этого применяются следующие "магческие команды":

* `%time` — длительность выполнения отдельного оператора;
* `%timeit` — длительность выполнения отдельного оператора при неоднократном повторе, для большей точности;
* `%prun` — выполнение кода с использованием профилировщика;
* `%lprun` — пошаговое выполнение кода с применением профилировщика;
* `%memit` — оценка использования оперативной памяти для отдельного оператора;
* `%mprun` — пошаговое выполнение кода с применением профилировщика памяти.


Пример работы команды `%timeit` рассмотрен выше. Он позволяет оценивать время выполнения однострочных инструкций, выполняя многократный их запуск.

In [266]:
%timeit sum(range(100))

2.04 µs ± 271 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Если же нужно оценить время, которое затрачивается на выполнение нескольких строк кода, нужно использовать команду с двумя знаками `%` - `%%timeit`:

In [267]:
%%timeit
    total = 0
    for i in range(1000):
        for j in range(1000):
            total += i * (-1) ** j

721 ms ± 51.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Для некоторых фрагментов кода будет полезно оценивать их длительность работы только по одному запуску. Для этого можно применять команду `%time` или `%%time` для многострочного фрагмента:

In [268]:
%%time
    total = 0
    for i in range(1000):
        for j in range(1000):
            total += i * (-1) ** j

Wall time: 897 ms


Программы состоят из множества отдельных операторов, и иногда оценка времени их выполнения в контексте важнее, чем по отдельности. В языке Python имеется встроенный профилировщик кода (о котором можно прочитать в документации 
языка Python), но оболочка IPython предоставляет намного более удобный способ его использования в виде «магической» функции `%prun`. Для пошагового профилирования может использоваться функция `%lprun`. Аналогично для профилирования объема используемой оперативной памяти могут применяться команды  `%memit` и `%mprun`. Подробную информацию  них можно узнать воспользовавшись справкой по этим командам.

### Основы Python

Данный блокнот представляет собой адаптированную версию блокнота http://cs231n.github.io/python-numpy-tutorial.

#### Введение

Python - отличный язык программирования общего назначения, а с помощью нескольких популярных библиотек (numpy, scipy, matplotlib) он становится мощной средой для научных вычислений.

Мы ожидаем, что у многих из вас уже есть некоторый опыт работы с Python и numpy; для остальных вас этот раздел будет служить быстрым курсом знакомства как с языком программирования Python, так и использования Python для научных вычислений.

Кто-то из вас знаком с Matlab, и в этом случае мы также рекомендуем страницу numpy для пользователей Matlab (https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html ).

Будут рассмотрены:
* Основы языка Python: основные типы данных (контейнеры, списки, словари, наборы, кортежи), функции, классы
* Библиотека Numpy: массивы, индексирование массивов, типы данных, математика массивов, трансляция

#### Основы языка Python

Python - высокоуровневый, динамически типизированный язык программирования. Код Python часто называют псевдокодом, поскольку он позволяет вам выражать мощные алгоритмы в нескольких строках кода, оставаясь очень читабельным. В качестве примера рассмотрим реализацию классического алгоритма быстрой сортировки в Python:

In [269]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]


#### Версии Python

В настоящее время существуют две поддерживаемых версии Python - 2.7 и 3.6. В Python 3.0 добавлено много обратно несовместимых изменений, поэтому код, написанный для версии 2.7, может не работать под 3.6 и наоборот. Для этого класса весь код будет использовать Python 3.6.

Вы можете проверить свою версию Python в командной строке, запустив `python -V`.

#### Основные типы данных

##### Числа

Целые числа и числа с плавающей запятой работают так, как и в других языках:

In [270]:
x = 3
print(x, type(x))

3 <class 'int'>


In [271]:
print(x + 1)   # Addition;
print(x - 1)   # Subtraction;
print(x * 2)   # Multiplication;
print(x ** 2)  # Exponentiation;

4
2
6
9


In [272]:
x += 1
print(x)  # Prints "4"
x *= 2
print(x)  # Prints "8"

4
8


In [273]:
y = 2.5
print(type(y)) # Prints "<type 'float'>"
print(y, y + 1, y * 2, y ** 2) # Prints "2.5 3.5 5.0 6.25"

<class 'float'>
2.5 3.5 5.0 6.25


Обратите внимание: в отличие от многих языков Python не имеет унарных инкрементов (x++) или декрементов (x--).
Python также имеет встроенные типы для длинных целых чисел и комплексных чисел.

##### Логические переменные

Python реализует все обычные операторы для булевой логики, но использует английские слова, а не символы (`&&`, `||` и т. д.):

In [274]:
t, f = True, False
print(type(t)) # Prints "<type 'bool'>"

<class 'bool'>


Теперь давайте посмотрим на операции:

In [275]:
print(t and f) # Logical AND;
print(t or f)  # Logical OR;
print(not t)   # Logical NOT;
print(t != f)  # Logical XOR;

False
True
False
True


##### Строки

In [276]:
hello = 'hello'   # String literals can use single quotes
world = "world"   # or double quotes; it does not matter.
print(hello, len(hello))

hello 5


In [277]:
hw = hello + ' ' + world  # String concatenation
print(hw)  # prints "hello world"

hello world


In [278]:
hw12 = '%s %s %d' % (hello, world, 12)  # sprintf style string formatting
print(hw12)  # prints "hello world 12"

hello world 12


Строковые объекты имеют множество полезных методов; например:

In [279]:
s = "hello"
print(s.capitalize())  # Capitalize a string; prints "Hello"
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print(s.center(7))     # Center a string, padding with spaces; prints " hello "
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                               # prints "he(ell)(ell)o"
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


Вы можете найти список всех строковых методов в [документации](https://docs.python.org/3/library/stdtypes.html#string-methods).

#### Контейнеры

Python включает несколько встроенных типов контейнеров: списки, словари, множества и кортежи.

##### Списки

Список представляет собой эквивалент массива в Python, но может изменять размер и может содержать элементы разных типов:

In [280]:
xs = [3, 1, 2]   # Create a list
print(xs, xs[2])
print(xs[-1])     # Negative indices count from the end of the list; prints "2"

[3, 1, 2] 2
2


In [281]:
xs[2] = 'foo'    # Lists can contain elements of different types
print(xs)

[3, 1, 'foo']


In [282]:
xs.append('bar') # Add a new element to the end of the list
print(xs)  

[3, 1, 'foo', 'bar']


In [283]:
x = xs.pop()     # Remove and return the last element of the list
print(x, xs) 

bar [3, 1, 'foo']


Как обычно, вы можете найти все подробные сведения о списках в [документации](https://docs.python.org/3/tutorial/datastructures.html#more-on-lists).

##### Срезы

Помимо доступа к элементам списка по одному, Python обеспечивает краткий синтаксис для доступа к подспискам; это называется срезами:

In [284]:
nums = list(range(5))    # range is a built-in function that creates a list of integers
print(nums)         # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])    # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])     # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])     # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])      # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print(nums[:-1])    # Slice indices can be negative; prints ["0, 1, 2, 3]"
nums[2:4] = [8, 9] # Assign a new sublist to a slice
print(nums)         # Prints "[0, 1, 8, 9, 4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


##### Циклы

Вы можете перебирать элементы списка следующим образом:

In [285]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

cat
dog
monkey


Если вы хотите получить доступ к индексу каждого элемента в теле цикла, используйте встроенную функцию `enumerate`:

In [286]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))

#1: cat
#2: dog
#3: monkey


##### Списковое включение

При программировании часто мы хотим преобразовать один тип данных в другой. В качестве простого примера рассмотрим следующий код, который вычисляет квадрат чисел:

In [287]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)

[0, 1, 4, 9, 16]


Вы можете сделать этот код проще, используя включение списка:

In [288]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)

[0, 1, 4, 9, 16]


В списковом включении могут также содержаться условия:

In [289]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)

[0, 4, 16]


##### Словари

Словарь хранит пары (ключ, значение), похожие на `Map` в Java или `object` в Javascript. Вы можете использовать его следующим образом:

In [290]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in d)     # Check if a dictionary has a given key; prints "True"

cute
True


In [291]:
d['fish'] = 'wet'    # Set an entry in a dictionary
print(d['fish'])      # Prints "wet"

wet


In [294]:
print(d['monkey'])  # KeyError: 'monkey' not a key of d

KeyError: 'monkey'

In [295]:
print(d.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(d.get('fish', 'N/A'))    # Get an element with a default; prints "wet"

N/A
wet


In [296]:
del d['fish']        # Remove an element from a dictionary
print(d.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"

N/A


Вы можете найти все, что вам нужно знать о словарях в [документации](https://docs.python.org/3/library/stdtypes.html#dict).


Легко перебирать ключи в словаре:

In [297]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


Если вы хотите получить доступ к ключам и их соответствующим значениям, используйте метод items:

In [298]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A %s has %d legs' % (animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


Словарные включения: они похожи на списковые включения, но позволяют легко создавать словари. Например:

In [299]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)

{0: 0, 2: 4, 4: 16}


##### Множества

Множество представляет собой неупорядоченный набор отдельных элементов. В качестве простого примера рассмотрим следующее:

In [300]:
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"


True
False


In [301]:
animals.add('fish')      # Add an element to a set
print('fish' in animals)
print(len(animals))       # Number of elements in a set;

True
3


In [302]:
animals.add('cat')       # Adding an element that is already in the set does nothing
print(len(animals))       
animals.remove('cat')    # Remove an element from a set
print(len(animals))       

3
2


_Циклы_: Итерация по множеству имеет тот же синтаксис, что и итерация по списку; однако, поскольку множества неупорядочены, вы не можете знать о порядке, в котором вы выбираете элементы набора:

In [303]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))
# Prints "#1: fish", "#2: dog", "#3: cat"

#1: fish
#2: cat
#3: dog


Включения множества. Подобно спискам и словарям, мы можем легко создавать меножества с использованием влючения множества:

In [304]:
from math import sqrt
print({int(sqrt(x)) for x in range(30)})

{0, 1, 2, 3, 4, 5}


##### Кортежи

Кортеж представляет собой упорядоченный список значений. Кортеж во многом похож на список; одним из наиболее важных различий является то, что кортежи могут использоваться как ключи в словарях и как элементы множеств, в то время как списки не могут. Вот простой пример:

In [305]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)       # Create a tuple
print(type(t))
print(d[t])       
print(d[(1, 2)])

<class 'tuple'>
5
1


In [306]:
t[0] = 1

TypeError: 'tuple' object does not support item assignment

#### Функции

Функции Python определяются с помощью ключевого слова `def`. Например:

In [307]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


Мы часто будем определять функции с необязательными аргументами, например:

In [308]:
def hello(name, loud=False):
    if loud:
        print('HELLO, %s!' % name.upper())
    else:
        print('Hello, %s' % name)

hello('Bob')
hello('Fred', loud=True)

Hello, Bob
HELLO, FRED!


#### Классы


Синтаксис для определения классов в Python прост:

In [309]:
class Greeter:

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"

Hello, Fred
HELLO, FRED!


##### <font color='red'>Задание</font>

Создать класс, реализующий функционал учета рейтинга студентов **StudentsRaiting**. Класс должен иметь конструктор, который будет принимать список студентов с результатами сданных экзаменов, реализованый в виде словаря с ключем "ФИО студента" и оценками по экзаменам по 4 предметам (Программирование, Дискретная математика, Иностранный язык, Философия), представленными в виде упорядоченного множества (кортежа). Например:

`{"Иванов Петр Николавич":(3,3,5,4), "Петров Иван Константинович":(5,4,5,4)}`

Релизовать методы: 
- добавления студента с оценками по экзаменам
- удаления студента из рейтинга 
- получения списка студентов с рейтингом выше порогового
- метод демонстрации работы методов класса с выводом результатов на печать в виде текстовой таблицы.

Примечание:
Рейтинг составляется по суммарному баллу по всем предметам.

In [1]:
class StudentsRating:
    
    def __init__(self, students):
        self.students = students      
                
    def add_student(self, name, marks):
        if name in self.students:
            return
        self.students[name]=marks
        print("Студент ", name, " добавлен!\n")
        
    def remove_student(self, name):
        if name in self.students:
            del self.students[name]
            print("Студент ", name, " удален!\n")
        
    def filter_students(self, limit):
        filtered_students = []
        for key in self.students:
            marks = self.students[key]
            marks_sum = sum(marks)
            if(marks_sum>=limit):
                filtered_students.append((key, marks_sum))
                
        return filtered_students
                
    def print(self):
        print("ФИО\tРейтинг\n")
        for key in self.students:
            marks = self.students[key]
            marks_sum = sum(marks)
            print(key, "\t", marks_sum)
            
            
initial_rating = StudentsRating({"Иванов Петр Николавич":(3,3,5,4), "Петров Иван Константинович":(5,4,5,4)})
initial_rating.print()
print("\n")
initial_rating.add_student("Сидоров Василий Федорович", (1,1,2,3))
initial_rating.add_student("Петухов Василий Николаевич", (4,2,3,3))
initial_rating.print()
print("\n")
initial_rating.remove_student("Сидоров Василий Федорович")
initial_rating.print()


print(initial_rating.filter_students(14))


ФИО	Рейтинг

Иванов Петр Николавич 	 15
Петров Иван Константинович 	 18


Студент  Сидоров Василий Федорович  добавлен!

Студент  Петухов Василий Николаевич  добавлен!

ФИО	Рейтинг

Иванов Петр Николавич 	 15
Петров Иван Константинович 	 18
Сидоров Василий Федорович 	 7
Петухов Василий Николаевич 	 12


Студент  Сидоров Василий Федорович  удален!

ФИО	Рейтинг

Иванов Петр Николавич 	 15
Петров Иван Константинович 	 18
Петухов Василий Николаевич 	 12
[('Иванов Петр Николавич', 15), ('Петров Иван Константинович', 18)]


### Numpy

Numpy - это основная библиотека для научных вычислений на Python. Он предоставляет высокопроизводительный объект многомерных массивов и инструменты для работы с этими массивами. Если вы уже знакомы с MATLAB, то можно ознакомиться с эти [материалом](http://wiki.scipy.org/NumPy_for_Matlab_Users), полезным для начала работы с Numpy.

Чтобы использовать Numpy, сначала нужно импортировать пакет `numpy`:

In [311]:
import numpy as np

#### Массивы

Массив numpy представляет собой сетку значений одного типа и индексируется кортежем неотрицательных целых чисел. Число измерений - это ранг массива; форма массива представляет собой набор целых чисел, дающий размер массива вдоль каждого измерения.

Мы можем инициализировать массивы numpy из списков Python и обращаться к элементам с использованием квадратных скобок:

In [312]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)                  

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [313]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

[[1 2 3]
 [4 5 6]]


In [314]:
print(b.shape)                   
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


Numpy также предоставляет множество функций для создания массивов:


In [315]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [316]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

[[1. 1.]]


In [317]:
c = np.full((2,2), 7) # Create a constant array
print(c) 

[[7 7]
 [7 7]]


In [318]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

[[1. 0.]
 [0. 1.]]


In [319]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0.77834548 0.94957105]
 [0.66252687 0.01357164]]


#### Типы данных

Каждый массив numpy представляет собой набор элементов одного типа. Numpy предоставляет большой набор числовых типов данных, которые можно использовать для построения массивов. Numpy пытается угадать тип данных при создании массива, но функции, которые строят массивы, обычно также включают необязательный аргумент, чтобы явно указать тип данных. Например:

In [320]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int32 float64 int64


Вы можете прочитать все о типах данных numpy в [документации](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

#### Атрибуты массивов

При работе с массивами библиотеки NumPy можно получить полезную информацию о форме, размерностях массива, о типах данных элементов и занимаемом объеме данных.

In [1]:
import numpy as np
np.random.seed(0)  # начальное значение для целей воспроизводимости
x1 = np.random.randint(10, size=6)          # одномерный массив
x2 = np.random.randint(10, size=(3, 4))     # двумерный массив
x3 = np.random.randint(10, size=(3, 4, 5))  # трехмерный массив

In [322]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [323]:
print("dtype:", x3.dtype)

dtype: int32


In [324]:
print("itemsize:", x3.itemsize, "bytes")

itemsize: 4 bytes


In [325]:
 print("nbytes:", x3.nbytes, "bytes")

nbytes: 240 bytes


##### <font color=red>Задание</font>
Создать массив значений типа `int32` размером 10х10, состоящий из равномерно распределенных случайных чисел от 0 до 100. Получить 4 копии этого массива со значениями типа `uint32`,`int64`,`uint64`,`float`. Для каждого массива вывести сведения: число размерностей, форма, размер, тип данных, размер каждого значения в байтах и размер всего массива в байтах.


In [22]:
# Выполнение задания

arr = np.random.randint(100, size=(10,10))

def print_props(x3):
    print("ndim: ", x3.ndim)
    print("shape:", x3.shape)
    print("size: ", x3.size)
    print("dtype:", x3.dtype)
    print("itemsize:", x3.itemsize, "bytes")
    print("nbytes:", x3.nbytes, "bytes")
    print()
    

uint32_arr = np.array(arr, dtype=np.uint32)
int64_arr = np.array(arr, dtype=np.int64)
uint64_arr = np.array(arr, dtype=np.uint64)
float_arr = np.array(arr, dtype=np.float)

print_props(arr)
print_props(uint32_arr)
print_props(int64_arr)
print_props(uint64_arr)
print_props(float_arr)

ndim:  2
shape: (10, 10)
size:  100
dtype: int32
itemsize: 4 bytes
nbytes: 400 bytes

ndim:  2
shape: (10, 10)
size:  100
dtype: uint32
itemsize: 4 bytes
nbytes: 400 bytes

ndim:  2
shape: (10, 10)
size:  100
dtype: int64
itemsize: 8 bytes
nbytes: 800 bytes

ndim:  2
shape: (10, 10)
size:  100
dtype: uint64
itemsize: 8 bytes
nbytes: 800 bytes

ndim:  2
shape: (10, 10)
size:  100
dtype: float64
itemsize: 8 bytes
nbytes: 800 bytes



#### Индексация массивов

Numpy предлагает несколько способов индексации в массивах.

**Срезы**: Подобно спискам Python, с массивами numpy можно выполнять срезы. Поскольку массивы могут быть многомерными, вы должны указать срез для каждого измерения массива:

In [327]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


Срез массива является представлением исходных данных, поэтому его изменение изменит исходный массив.

In [328]:
print(a[0, 1])  
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) 

2
77



Вы также можете комбинировать индексирование целыми числами с индексацией срезами. Однако при этом будет получен массив меньшего ранга, чем исходный массив. Обратите внимание, что это сильно отличается от того, как MATLAB обрабатывает срез массива:

In [329]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Два способа доступа к данным в средней строке массива.
Смешивание целых индексов с индексацией срезами дает массив более низкого ранга,
в то время как использование только срезов дает массив того же ранга, что и
исходный массив:

In [330]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape) 
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


##### <font color=red>Задание</font>
Выполнить следующий код и объяснить результат.

In [10]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[2 4 6] (3,)

[[2]
 [4]
 [6]] (3, 1)


*Написать обьяснение:*

В первом случае используется целое число для индексации, а во втором случае срез.

**Целочисленное индексирование массива**: при индексировании в массивах numpy с использованием срезов результирующее представление массива всегда будет подмассивом исходного массива. 
Напротив, индексирование целыми числами позволяет создавать произвольные массивы с использованием данных из другого массива. Например:

In [332]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and 
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


In [333]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


Один полезный трюк с индексированием целочисленного массива - это выбор или изменение одного элемента из каждой строки матрицы:

In [334]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [335]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

[ 1  6  7 11]


In [336]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


Иногда при индексации при помощи срезов бывает полезно работать не с представлением исходного массива, а иметь новый независимый массив данных из исходного массива. Т.е. нужно скопировать представление массива при помощи метода `copy`.

In [337]:
x = np.random.randint(10,size=(3,4))
x_sub_copy = x[:2, :2].copy()
print(x_sub_copy)

[[4 3]
 [8 4]]


**Индексирование при помощи булевых массивов**: индексирование при помощи булевых массивов позволяет выбирать произвольные элементы массива. Часто этот тип индексации используется для выбора элементов массива, которые удовлетворяют некоторому условию. Вот пример:

In [3]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [4]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

[3 4 5 6]
[3 4 5 6]


##### <font color=red>Задание</font>
Создать массив случайных целочисленных значений (от -100 до 100) размером 8x8. Используя индексацию булевыми массивами получить:
1. Все элементы, значения которых являются четными числами. Вывести их маску в массиве.
2. Все элементы, значения которых попадают в диапазон от 10 до 50. Вывести их маску в массиве.
3. Все элементы, значения которых являются четными числами и попадают в диапазон от 10 до 50. Вывести их маску в массиве.
4. Все элементы, значения которых являются нечетными числами и модуль значения которых из диапазона от 10 до 50. Вывести их маску в массиве.
5. Все элементы, значения которых являются нечетными числами или отрицательными.

In [19]:
import math
a = np.random.randint(low=-10, high=100,size=(8,8))

even = (a % 2 == 0)
print("Even:", even)
print(a[even])

between_10_and_50 = (a>=10) & (a<=50)
print("Between 10 and 50", between_10_and_50)
print(a[between_10_and_50])

even_between_10_and_50 = even & between_10_and_50
print("All even between 10 and 50", even_between_10_and_50 )
print(a[even_between_10_and_50])

odd = (a % 2 > 0)
in_range = (abs(a)>=10) & (abs(a)<=50)
in_range_odd = odd & in_range
print("All odd and abs between 10 and 50", in_range_odd)
print(a[in_range_odd])

negative = (a < 0)
negative_or_odd = negative | odd
print("All odd or negative",negative_or_odd)
print(a[negative_or_odd])

Even: [[ True  True  True  True  True  True  True  True]
 [False False  True  True False  True  True  True]
 [ True False False False False  True False  True]
 [False False  True  True  True  True  True False]
 [False False  True False  True False  True  True]
 [ True False False False False  True  True  True]
 [ True  True  True  True False  True False False]
 [ True False  True False  True  True False  True]]
[52 44 68 48 60 76 12  8 34 60 58 18 -6 60 94 70 42 94  0 -4 58 18 36 46
 78 60 56 64 82 96 94  8 24 90 74 28 28 16 36]
Between 10 and 50 [[False  True False  True False False  True False]
 [ True  True  True False False False  True False]
 [False  True  True False  True False False False]
 [ True  True  True False False False False  True]
 [False  True  True False  True  True  True False]
 [False False False  True False False False False]
 [False False False  True  True False  True False]
 [False  True  True False  True  True False  True]]
[44 48 12 49 25 34 18 13 33 29 27 39 4

Для краткости мы пропустили много деталей о индексации массива numpy; если вы хотите узнать больше, прочитайте документацию.

#### Изменение формы массивов

Часто требуется изменить форму массива (количество размерностей и их емкость), не изменяя самих элементов массива. Для этого используется специальный метод `reshape`.

In [340]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Другой часто используемый паттерн изменения формы — преобразование одномерного массива в двумерную матрицу-строку или матрицу-столбец. Для этого можно применить метод reshape, но лучше воспользоваться ключевым словом newaxis при выполнении операции среза:

In [341]:
x = np.array([1, 2, 3]) 
# Преобразование в вектор-строку с помощью reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [342]:
# Преобразование в вектор-строку посредством newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [343]:
# Преобразование в вектор-столбец с помощью reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [344]:
# Преобразование в вектор-столбец посредством newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

#### Объединение массивов

Для работы с массивами с различающимися измерениями удобно использовать функции `np.vstack` (вертикальное объединение) и `np.hstack` (горизонтальное объединение):


In [345]:
 x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],[6, 5, 4]])
# Объединяет массивы по вертикали
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [346]:
# Объединяет массивы по горизонтали
y = np.array([[99],[99]])
np.hstack([grid, y])


array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

Функция `np.dstack` аналогично объединяет массивы по третьей оси.

#### Разбиение массивов
Противоположностью слияния является разбиение, выполняемое с помощью функций np.split, np.hsplit и np.vsplit. Каждой из них необходимо передавать список индексов, задающих точки раздела:

In [347]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


Функции `np.hsplit` и `np.vsplit` действуют аналогично:

In [348]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [349]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [350]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


##### <font color=red>Задание</font>
Написать функцию, которая из исходного массива размером 8х8 получает (при помощи операций разбиения и объединения) массив, в котором переставлены квадранты 1-й с 3-м, 2-й с 4-м по сравнению с исходным массивом. Продемонстрировать работу функции все шаги алгоритма сопроводить подробными комментариями и отладочным выводом промежуточных результатов.

Т.е. например из массива

`[[49  5 49  1 28 27 31 35]
 [21 12 34  3 20  2 42 48]
 [21 22 39 23 28 31 47 34]
 [37  6 24 22 19 32 27 20]
 [12  0  1 40  2 30 42 47]
 [33 40 10  8 29 48 24  8]
 [14 49  8 46 23 18 10 49]
 [15 20 49 30  9 18 42  5]]`
 
должен получиться массив 

 `[[ 2 30 42 47 12  0  1 40]
 [29 48 24  8 33 40 10  8]
 [23 18 10 49 14 49  8 46]
 [ 9 18 42  5 15 20 49 30]
 [28 27 31 35 49  5 49  1]
 [20  2 42 48 21 12 34  3]
 [28 31 47 34 21 22 39 23]
 [19 32 27 20 37  6 24 22]]`

In [9]:
# Выполнение задания
arr = np.array([[49,  5, 49,  1, 28, 27, 31, 35],
 [21, 12, 34,  3, 20,  2, 42, 48],
 [21, 22, 39, 23, 28, 31, 47, 34],
 [37,  6, 24, 22, 19, 32, 27 ,20],
 [12 , 0,  1, 40,  2, 30, 42 ,47],
 [33 ,40, 10,  8, 29, 48, 24 , 8],
 [14, 49,  8, 46, 23 ,18, 10 ,49],
 [15, 20, 49, 30,  9, 18, 42  ,5]])

left, right = np.hsplit(arr, [4])

print("Left:", left)
print("Right:", right)

top_left, bottom_left = np.vsplit(left,[4])
print("Top Left:", top_left)
print("Bottom Left:", bottom_left)
top_right, bottom_right = np.vsplit(right,[4])
print("Top Right:", top_right)
print("Bottom Right:", bottom_right)

top = np.hstack([bottom_right, bottom_left])
bottom = np.hstack([top_right,top_left])

result = np.vstack([top, bottom])

print("Result", result)

Left: [[49  5 49  1]
 [21 12 34  3]
 [21 22 39 23]
 [37  6 24 22]
 [12  0  1 40]
 [33 40 10  8]
 [14 49  8 46]
 [15 20 49 30]]
Right: [[28 27 31 35]
 [20  2 42 48]
 [28 31 47 34]
 [19 32 27 20]
 [ 2 30 42 47]
 [29 48 24  8]
 [23 18 10 49]
 [ 9 18 42  5]]
Top Left: [[49  5 49  1]
 [21 12 34  3]
 [21 22 39 23]
 [37  6 24 22]]
Bottom Left: [[12  0  1 40]
 [33 40 10  8]
 [14 49  8 46]
 [15 20 49 30]]
Top Right: [[28 27 31 35]
 [20  2 42 48]
 [28 31 47 34]
 [19 32 27 20]]
Bottom Right: [[ 2 30 42 47]
 [29 48 24  8]
 [23 18 10 49]
 [ 9 18 42  5]]
Result [[ 2 30 42 47 12  0  1 40]
 [29 48 24  8 33 40 10  8]
 [23 18 10 49 14 49  8 46]
 [ 9 18 42  5 15 20 49 30]
 [28 27 31 35 49  5 49  1]
 [20  2 42 48 21 12 34  3]
 [28 31 47 34 21 22 39 23]
 [19 32 27 20 37  6 24 22]]


#### Вычисления с массивами

Основные математические функции работают поэлементно с массивами и доступны как в виде перегрузок операторов, так и как функций в модуле numpy:

In [351]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [352]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [353]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [354]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [355]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


Обратите внимание, что в отличие от MATLAB, * является поэлементным умножением, а не матричным умножением. Вместо этого мы используем функцию точки для вычисления скалярных произведений векторов, умножения вектора на матрицу и умножения матриц. точка доступна как функция в модуле numpy, так и как метод экземпляра объектов массива:

In [356]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


In [357]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [358]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy предоставляет множество полезных функций для выполнения вычислений с массивами; одна из самых полезных - это `sum`:

In [359]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


Полный список математических функций, предоставляемых numpy, содержится в [документации](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Помимо вычисления математических функций с использованием массивов, нам часто приходится изменять форму масива или иным образом манипулировать данными в массивах. Простейшим примером такой операции является транспонирование матрицы; для транспонирования матрицы просто используйте атрибут T объекта массива:

In [360]:
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [361]:
v = np.array([1,2,3])
print(v) 
print(v.T)

[1 2 3]
[1 2 3]


#### Трансляция

Трансляция - мощный механизм, позволяющий numpy работать с массивами разных форм при выполнении арифметических операций. Часто мы имеем меньший массив и больший массив, и мы хотим использовать меньший массив несколько раз, чтобы выполнить некоторую операцию над большим массивом.

Например, предположим, что мы хотим добавить постоянный вектор в каждую строку матрицы. Мы могли бы сделать это следующим образом:

In [362]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Это работает; однако, когда матрица x очень велика, вычисление явного цикла в Python может быть медленным. Заметим, что добавление вектора v в каждую строку матрицы x эквивалентно формированию матрицы vv путем стыковки нескольких копий v по вертикали, а затем выполнения поэлементного суммирования x и vv. Мы могли бы реализовать этот подход следующим образом:

In [363]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [364]:
y = x + vv  # Add x and vv elementwise
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Трансляция позволяет нам выполнять это вычисление без фактического создания нескольких копий v. Рассмотрим этот вариант, использующий трансляцию:

In [365]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Строка `y = x + v` работает, даже если` x` имеет форму `(4, 3)` и `v` имеет форму` (3,) `из-за широковещания; эта строка работает так, как если бы v фактически имела форму `(4, 3)`, где каждая строка была копией `v`, а сумма выполнялась поэлементно.

**Трансляция** двух массивов выполняется в соответствии с правилами:

1. Если массивы не одного ранга, к форме массива меньшего ранга добавляется одно измерение слева до тех пор, пока формы массивов не будут иметь одинаковую длину.
2. Два массива, как говорят, совместимы в некотором измерении, если они имеют одинаковый размер в этом измерении, или если один из массивов имеет размер 1 в этом измерении.
3. Массивы могут транслироваться друг с другом, если они совместимы во всех измерениях.
4. После трансляции каждый массив ведет себя так, как если бы он имел форму, равную поэлементному максимуму форм двух входных массивов.
5. В любом измерении, где один массив имел размер 1, а другой массив имел размер больше 1, первый массив ведет себя так, как если бы он был скопирован вдоль этого измерения.

В книге `Python Data Science Handbook: Essential Tools for Working with Data` под авторством `Jake VanderPlas` трансляция массивов описывается тремя правилами:
1. Если размерность двух массивов отличается, форма массива с меньшей размерностью дополняется единицами с ведущей (левой) стороны.
2. Если форма двух массивов не совпадает в каком-то измерении, массив с формой, равной 1 в данном измерении, растягивается вплоть до соответствия форме другого массива.
3. Если в каком-либо измерении размеры массивов различаются и ни один не равен 1, генерируется ошибка.

Если это объяснение непонятно, попробуйте прочитать объяснение из [документации](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) или этого [объяснения](http: // wiki.scipy.org/EricsBroadcastingDoc).

Вот некоторые примеры использования трансляции:

In [366]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [367]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

[[2 4 6]
 [5 7 9]]


In [368]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [369]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [370]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


Трансляция обычно делает ваш код более кратким и быстрым, поэтому вы должны стремиться использовать его там, где это возможно.

##### Трансляция. Пример 1.

Рассмотрим сложение двумерного массива с одномерным:
``` 
M = np.ones((2, 3))
a = np.arange(3)
```
Рассмотрим эту операцию подробнее. Формы массивов следующие:
```
M.shape = (2, 3)
a.shape = (3,)
```
По правилу 1, поскольку размерность массива a меньше, мы дополняем его из-
мерениями слева:
```
M.shape -> (2, 3)
a.shape -> (1, 3)
```
По правилу 2 мы видим, что первое измерение массивов различается, так что мы 
растягиваем его вплоть до совпадения:
```
M.shape -> (2, 3)
a.shape -> (2, 3)
```
Формы совпадают, и мы видим, что итоговая форма будет (2, 3). Проверим:

In [371]:
M = np.ones((2, 3))
a = np.arange(3)
M+a

array([[1., 2., 3.],
       [1., 2., 3.]])

##### Транслирование. Пример 2
Рассмотрим пример, в котором необходимо транслировать оба массива:
```
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
```
Начнем с записи формы наших массивов:
```
a.shape = (3, 1)
b.shape = (3,)
```
Правило 1 гласит, что мы должны дополнить форму массива b единицами:
```
a.shape -> (3, 1)
b.shape -> (1, 3)
```
Правило 2 говорит, что нужно увеличивать эти единицы вплоть до совпадения 
с размером другого массива:
```
a.shape -> (3, 3)
b.shape -> (3, 3)
```
Поскольку результаты совпадают, формы совместимы. Получаем:


In [372]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

##### Транслирование. Пример 3
Рассмотрим пример, в котором два массива несовместимы:
```
M = np.ones((3, 2))
a = np.arange(3)
```
Эта ситуация лишь немного отличается от примера 1: матрица M транспонирована. Какое же влияние это окажет на вычисления? Формы массивов следующие:
```
M.shape = (3, 2)
a.shape = (3,)
```
Правило 1 требует от нас дополнить форму массива a единицами:
```
M.shape -> (3, 2)
a.shape -> (1, 3)
```
Согласно правилу 2 первое измерение массива a растягивается, чтобы соответствовать таковому массива M:
```
M.shape -> (3, 2)
a.shape -> (3, 3)
```
Теперь вступает в действие правило 3 — итоговые формы не совпадают, так что массивы несовместимы, что мы и видим, попытавшись выполнить данную операцию:

In [373]:
M = np.ones((3, 2))
a = np.arange(3)
M+a

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

Обратите внимание на имеющийся потенциальный источник ошибки: можно было бы сделать массивы a и M совместимыми, скажем путем дополнения формы a единицами справа, а не слева. Но правила транслирования работают не так! 
Если вам хочется применить правостороннее дополнение, можете сделать это явным образом, поменяв форму массива. Для этого воспользуемся ключевым словом `np.newaxis`:

In [374]:
a[:, np.newaxis].shape

(3, 1)

In [375]:
M + a[:, np.newaxis]

array([[1., 1.],
       [2., 2.],
       [3., 3.]])

Этом краткий обзор затронул многие важные вещи, которые вам нужно знать о numpy, но далеко не все. Смотрите [документацию по numpy](http://docs.scipy.org/doc/numpy/reference/), чтобы узнать больше о numpy.

##### <font color=red>Задание</font>
Возможна ли совместная трансляция массивов с формами:
1. (100,100,4) и (3) ?
2. (15,1,6,5) и (7,1,5) ?
3. (12,3,8) и (3,1) ?
4. (10,4,1,6) и (3,1,6) ?
5. (10,1) и (1,10,3) ?

Дать подробные ответы (аналогично примерам, приведенным выше) со ссылками на правила трансляции и сопроводить примерами с вычислениями и комментариями.

In [376]:
# Выполнение задания.

# Первый случай - размерности массивов несовместимы, поэтому нельзя применить трансляцию.
# Трансляция второго массива:
# (3) -> (1,1,3) (прав.1) -> (100,100,3) (прав.2)
# Итоговые размерности: (100,100,4) и (100,100,3)
# По правилу 3 не совместимы

# Второй случай
# Трансляция второго массива:
# (7,1,5) -> (1,7,1,5) (прав.1) -> (15,7,1,5) (прав.2) 
# Итоговые размерности: (15,1,6,5) и (15,7,1,5)
# По правилу 2 оба массива совместимы

# Третий случай
# Трансляция второго массива:
# (3,1) -> (1,3,1) (прав.1) -> (12,3,1)  (прав.2)
# Итоговые размерности: (12,3,8) и (12,3,1)
# По правилу 2 оба массива совместимы

# Четвертый случай
# Трансляция второго массива:
# (3,1,6)->(1,3,1,6) -> (10,3,1,6)
# Итоговые размерности: (10,4,1,6) и (10,3,1,6)
# По правилу 3 не совместимы

# Пятый случай
# Трансляция первого массива:
#(10,1) -> (1,10,1)
# Итоговые размерности: (1,10,1) и (1,10,3)
# По правилу 2 оба массива совместимы

#### Универсальные функции

Функции, поддерживающие трансляцию, известны как **универсальные функции**. Вы можете найти список всех универсальных функций в [документации](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

**<font color=orange>Вычисления с применением векторизации посредством универсальных функций практически всегда более эффективны, чем их эквиваленты, реализованные с помощью циклов Python, особенно при росте размера массивов.</font>**

* Арифметические функции над массивами

In [377]:
 x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # деление с округлением в меньшую сторону
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


Дополнительно эти операции можно комбинировать любыми способами с соблюдением стандартного приоритета выполнения операций:


In [378]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

* Абсолютное значение.

Используется универсальная функция библиотеки NumPy — `np.absolute`, доступная также под псевдонимом `np.abs`:

In [379]:
np.absolute(x)

array([0, 1, 2, 3])

In [380]:
np.abs(x)

array([0, 1, 2, 3])

In [381]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

#### Указание массива для вывода результата
При больших вычислениях удобно задать массив, в котором будет сохранен результат вычисления. Вместо того чтобы создавать временный массив, можно воспользоваться этой возможностью для записи результатов вычислений непосредственно 
в нужное вам место памяти. Сделать это для любой универсальной функции можно с помощью аргумента out:

In [382]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


Эту возможность можно использовать даже вместе с представлениями массивов. Например, можно записать результаты вычислений в каждый второй элемент заданного массива:

In [383]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


Если бы мы вместо этого написали `y[::2] = 2 ** x`, был бы создан временный массив для хранения результатов операции `2 ** x` с последующим копированием этих значений в массив y. Для столь незначительных объемов вычислений особой разницы нет, но для очень больших массивов экономия памяти за счет аккуратного использования аргумента out может оказаться значительной.

##### <font color=red>Задание</font>
Создать класс наследник от класса учета рейтинга студентов (**StudentsRaiting**) и расширить его методами рассчета статистики по предметам (средний балл, максимальный балл, минимальный балл). Для этого нужно преобразовать данные об оценках из словаря в массив и использовать функции библиотеки Numpy.

Примечание: Использовать универсальные функции для работы с массивами numpy.

In [19]:
# Выполнение задания

class AdvancedRating(StudentsRating):
    def average(self):
        arr = np.array(list(self.students.values()))
        print("Средний балл:", np.mean(arr))
        means = np.mean(arr, axis=0)
        print("Средний балл по первому предмету:", means[0])
        print("Средний балл по второму предмету:", means[1])
        print("Средний балл по третьему предмету:", means[2])
        print("Средний балл по четвертому предмету:", means[3])
        
    def max(self):
        arr = np.array(list(self.students.values()))
        print("Максимальный балл:", np.max(arr))
        means = np.max(arr, axis=0)
        print("Максимальный балл по первому предмету:", means[0])
        print("Максимальный балл по второму предмету:", means[1])
        print("Максимальный балл по третьему предмету:", means[2])
        print("Максимальный балл по четвертому предмету:", means[3])
        
    def min(self):
        arr = np.array(list(self.students.values()))
        print("Минимальный балл:", np.min(arr))
        means = np.min(arr, axis=0)
        print("Минимальный по первому предмету:", means[0])
        print("Минимальный по второму предмету:", means[1])
        print("Минимальный по третьему предмету:", means[2])
        print("Минимальный по четвертому предмету:", means[3])
        
    
rating = AdvancedRating({"Иванов Петр Николавич":(3,3,5,4), "Петров Иван Константинович":(5,4,5,4)})
rating.add_student("Сидоров Василий Федорович", (1,1,2,3))
rating.add_student("Петухов Василий Николаевич", (4,2,3,3))

rating.average()
rating.max()
rating.min()

Студент  Сидоров Василий Федорович  добавлен!

Студент  Петухов Василий Николаевич  добавлен!

Средний балл: 3.25
Средний балл по первому предмету: 3.25
Средний балл по второму предмету: 2.5
Средний балл по третьему предмету: 3.75
Средний балл по четвертому предмету: 3.5
Максимальный балл: 5
Максимальный балл по первому предмету: 5
Максимальный балл по второму предмету: 4
Максимальный балл по третьему предмету: 5
Максимальный балл по четвертому предмету: 4
Минимальный балл: 1
Минимальный по первому предмету: 1
Минимальный по второму предмету: 1
Минимальный по третьему предмету: 2
Минимальный по четвертому предмету: 3


##### <font color=red>Задание</font>
0. Создать функцию `Function1(x)`, возвращающую вектор `y`, размер которого равен размеру вектора `x` и выполняющую поэлементное вычисление по формуле `y=1/(1+exp(-x)`. Создать функцию `Function2(x)`, возвращающую вектор `y`, размер которого равен размеру вектора `x` и выполняющую поэлементное вычисление по формуле `y=max(0,x)`.
1. Написать функцию `LinearTransform(M,x,b)`, где `M` - матрица, `x` - вектор, `b` - число. Функция должна ввозвращать вектор `y`, размер которого равен размеру вектора `x`, где `y` рассчитывается по формуле `y=M*x+b`, здесь под операцией `*` понимается операция скалярного произведения (dot product) матрицы на вектор.
2. Написать функцию `Transform(M1,M2,x,b1,b2)`, где `M1`,`M2` - матрицы, `x` - вектор, `b1`,`b2` - числа. Функция должна ввозвращать вектор `y`, размер которого равен размеру вектора `x`, где `y` рассчитывается по формуле `y=Function2(LinearTransform(M2,x2,b2))`, а `x2=Function1(LinearTransform(M1,x,b1))`.
3. Задать матрицы M1,M2 размером MxN, вектор размером N, и числа b1,b2 и выполнить вычисления `Transform(M1,M2,x,b1,b2)`, производя замеры времени выполнения функции. **Значения M и N нужно узнать у преподавателя.** 

Все функции задания нужно реализовать в двух вариантах: 
* с использованием универсальных векторизованных операций;
* с использованием циклов для вычислений.

Сравнить время выполнения для обеих реализаций и сделать выводы.

In [46]:
#Выполнение задания
import random
import math

M = 40
N = 40

M1_naive = [[random.random() for e in range(N)] for e in range(M)]
M2_naive = [[random.random() for e in range(N)] for e in range(M)]

#print("M1_naive:\n", M1_naive)
#print("M2_naive:\n", M2_naive)

M1_numpy = np.array(M1_naive)
M2_numpy = np.array(M2_naive)

#print("M1_numpy:\n", M1_numpy)
#print("M2_numpy:\n", M2_numpy)

x_naive = random.sample(range(100), N)
x_numpy = np.array(x_naive)

#print("X_naive:\n", x_naive)
#print("X_numpy:\n", x_numpy)

b1 = np.random.randint(100)
b2 = np.random.randint(100)

#print("b1:\n", b1)
#print("b2:\n", b2)

def Function1_naive(x):
    return [1/(1+math.exp(-i)) for i in x]

def Function2_naive(x):
    return [max(0,i) for i in x]

def LinearTransform_naive(M,x,b):
    result = [0 for i in range(len(x))]
    for i, row in enumerate(M):
        sum = 0
        for j, col in enumerate(row):
            sum = sum + col * x[j]
        result[i] = sum
    for index, elem  in enumerate(result):
        result[index]=elem+b
    return result

def Transform_naive(M1,M2,x,b1,b2):
    x2=Function1_naive(LinearTransform_naive(M1,x,b1))
    y=Function2_naive(LinearTransform_naive(M2,x2,b2))
    return y

def Function1_numpy(x):
    return 1/(1+np.exp(-x))

def Function2_numpy(x):
    return np.maximum(0,x)

def LinearTransform_numpy(M,x,b):
    return M.dot(x)+b

def Transform_numpy(M1,M2,x,b1,b2):
    x2=Function1_numpy(LinearTransform_numpy(M1,x,b1))
    y=Function2_numpy(LinearTransform_numpy(M2,x2,b2))
    return y

%timeit Transform_naive(M1_naive,M2_naive,x_naive,b1,b2)
%timeit Transform_numpy(M1_numpy, M2_numpy, x_numpy, b1,b2)

y_naive = Transform_naive(M1_naive,M2_naive,x_naive,b1,b2)
y_numpy = Transform_numpy(M1_numpy, M2_numpy, x_numpy, b1,b2)
            
#print(y_naive)
#print(y_numpy)




368 µs ± 15.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
15.1 µs ± 867 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
